#!/usr/bin/env python3
"""Refresh or validate the Feishu/Lark client documentation mirror.

The Feishu/Lark documentation site can be hard for coding agents to browse
reliably during implementation. This script crawls the official Open Platform
documentation directory endpoint, indexes the Developer Guides and Client API
roots, and mirrors the official markdown page content under
``references/client-docs-mirror/`` so OpenCode, Codex, and other generic agents
can query the documentation from the installed skill files.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import datetime as _dt
import hashlib
import json
import re
import shutil
import sys
import time
import urllib.parse
import urllib.request
from collections import Counter, defaultdict
from pathlib import Path

DOC_DIRECTORY_API = "https://open.feishu.cn/api/tools/docment/directory_list"
DOC_BASE = "https://open.feishu.cn/document"
ROOT_NAMES = {"\u5f00\u53d1\u6307\u5357": "Developer Guides", "\u5ba2\u6237\u7aef API": "Client API"}
USER_AGENT = "Hermes Feishu skill documentation crawler"
MIRROR_DIR_NAME = "client-docs-mirror"
MAX_WORKERS = 8
FAILURE_RATE_LIMIT = 0.05


def utc_now() -> str:
    return _dt.datetime.now(_dt.UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def fetch_json(url: str) -> dict:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode("utf-8"))


def fetch_text(url: str, attempts: int = 3) -> str:
    last_error: Exception | None = None
    for attempt in range(attempts):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
            with urllib.request.urlopen(req, timeout=45) as resp:
                return resp.read().decode("utf-8", "replace")
        except Exception as exc:  # pragma: no cover - network dependent
            last_error = exc
            time.sleep(0.5 * (attempt + 1))
    raise RuntimeError(f"failed to fetch {url}: {last_error}")


def safe_slug(text: str, fallback: str = "doc") -> str:
    text = urllib.parse.unquote(text)
    text = text.lower()
    text = re.sub(r"[^a-z0-9._-]+", "-", text)
    text = re.sub(r"-+", "-", text).strip("-._")
    return (text or fallback)[:80]


def section_key(full_path: str) -> str:
    parts = [p for p in full_path.split("/") if p]
    known = [
        "platform-overveiw",
        "develop-robots",
        "uMTMuMTMuMTM",
        "docs-add-on",
        "base-extensions",
        "block",
        "development-link-preview",
        "feishu-cards",
        "native-integration",
        "web-app-open-ability",
        "mcp_open_tools",
    ]
    for key in known:
        if key in parts:
            return key
    return parts[-2] if len(parts) > 1 else (parts[0] if parts else "root")


def percent_encode_path(path: str) -> str:
    return urllib.parse.quote(path, safe="/-._~ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789")


def mirror_path_for_doc(doc: dict) -> Path:
    encoded = percent_encode_path(doc["fullPath"])
    section = safe_slug(section_key(doc["fullPath"]), "section")
    digest = hashlib.sha1(encoded.encode("utf-8")).hexdigest()[:12]
    leaf = safe_slug(Path(doc["fullPath"]).name, "page")
    root = ROOT_NAMES.get(doc["trail"][0], "Other") if doc.get("trail") else "Other"
    root_slug = safe_slug(root, "root")
    return Path(MIRROR_DIR_NAME) / root_slug / section / f"{digest}-{leaf}.md"


def normalize_markdown(text: str) -> str:
    """Normalize generated mirror markdown enough for git diff hygiene."""
    lines = []
    for raw_line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n"):
        line = raw_line.rstrip()
        # Upstream markdown sometimes indents fenced code blocks with spaces
        # followed by a tab, which trips `git diff --check`. Preserve the
        # tab-indented code while removing only the leading spaces before tabs.
        line = re.sub(r"^ +\t", "\t", line)
        lines.append(line)
    return "\n".join(lines).rstrip() + "\n"


def mirror_one_doc(args: tuple[dict, Path]) -> dict:
    doc, staging_root = args
    encoded = percent_encode_path(doc["fullPath"])
    page_url = f"{DOC_BASE}{encoded}"
    markdown_url = f"{page_url}.md"
    rel_path = mirror_path_for_doc(doc)
    out_path = staging_root / rel_path.relative_to(MIRROR_DIR_NAME)
    text = fetch_text(markdown_url)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    header = "\n".join(
        [
            "<!--",
            "Mirrored official Feishu/Lark documentation page.",
            f"Source: {page_url}",
            f"Markdown source: {markdown_url}",
            "Generated by scripts/crawl_client_docs.py.",
            "-->",
            "",
        ]
    )
    out_path.write_text(normalize_markdown(header + text), encoding="utf-8")
    return {
        "source": page_url,
        "markdown_source": markdown_url,
        "path": str(rel_path),
        "bytes": out_path.stat().st_size,
    }


def walk(node: dict, trail: list[str], docs: list[dict]) -> None:
    name = node.get("name", "")
    full_path = node.get("fullPath", "")
    new_trail = trail + [name]
    if node.get("type") == "DocumentType":
        docs.append({"name": name, "fullPath": full_path, "trail": new_trail})
    for child in node.get("items") or []:
        walk(child, new_trail, docs)


def build_catalog(docs: list[dict], mirror_results: list[dict], failures: list[str]) -> str:
    lines = [
        "# Feishu/Lark Client Documentation Source Catalog",
        "",
        "Generated from the official Open Platform directory endpoint and markdown page URLs. This file maps official pages to mirrored markdown files stored inside this skill for coding-agent search and offline access.",
        "",
        f"- Directory source: `{DOC_DIRECTORY_API}`",
        "- Starting page checked: `https://open.feishu.cn/document/client-docs/intro`",
        f"- Document pages discovered: {len(docs)}",
        f"- Document pages mirrored: {len(mirror_results)}",
        f"- Failed pages: {len(failures)}",
        "- Roots indexed: Developer Guides and Client API",
        "- Mirror index: `references/client-docs-mirror-index.json`",
        "- Mirror root: `references/client-docs-mirror/`",
        "",
    ]

    for root_cn, root_en in ROOT_NAMES.items():
        root_docs = [d for d in docs if d["trail"] and d["trail"][0] == root_cn]
        groups: dict[str, list[dict]] = defaultdict(list)
        for doc in root_docs:
            groups[section_key(doc["fullPath"])].append(doc)
        lines.extend([f"## {root_en}", ""])
        for section in sorted(groups):
            lines.extend([f"### `{section}`", ""])
            for doc in sorted(groups[section], key=lambda item: item["fullPath"]):
                encoded = percent_encode_path(doc["fullPath"])
                rel = mirror_path_for_doc(doc)
                lines.append(f"- `{encoded}` -> `{rel}` -> {DOC_BASE}{encoded}")
            lines.append("")

    text = "\n".join(lines) + "\n"
    if re.search(r"[\u4e00-\u9fff]", text):
        raise SystemExit("generated catalog contains CJK characters; keep catalog headings English-only")
    return text


def validate_mirror(references: Path) -> list[str]:
    errors: list[str] = []
    mirror_root = references / MIRROR_DIR_NAME
    index_path = references / "client-docs-mirror-index.json"
    catalog_path = references / "client-docs-source-catalog.md"

    if not mirror_root.is_dir():
        return [f"missing mirror root: {mirror_root}"]
    if not index_path.is_file():
        return [f"missing mirror index: {index_path}"]
    if not catalog_path.is_file():
        errors.append(f"missing source catalog: {catalog_path}")

    index = json.loads(index_path.read_text(encoding="utf-8"))
    pages = index.get("pages") or []
    paths = [item.get("path", "") for item in pages]
    path_counts = Counter(paths)
    duplicate_paths = [path for path, count in path_counts.items() if count > 1]
    if duplicate_paths:
        errors.append(f"duplicate index paths: {duplicate_paths[:5]}")

    missing = []
    bad_bytes = []
    bad_headers = []
    trailing_ws = []
    for item in pages:
        rel = item.get("path")
        if not rel:
            errors.append(f"index entry missing path for source {item.get('source')}")
            continue
        if not rel.startswith(f"{MIRROR_DIR_NAME}/"):
            errors.append(f"index path outside mirror root: {rel}")
            continue
        path = references / rel
        if not path.is_file():
            missing.append(rel)
            continue
        size = path.stat().st_size
        if item.get("bytes") != size:
            bad_bytes.append((rel, item.get("bytes"), size))
        text = path.read_text(encoding="utf-8", errors="replace")
        if "Mirrored official Feishu/Lark documentation page." not in text[:500]:
            bad_headers.append(rel)
        if any(line.rstrip() != line for line in text.splitlines()):
            trailing_ws.append(rel)

    fs_files = sorted(str(path.relative_to(references)) for path in mirror_root.rglob("*.md"))
    extra = sorted(set(fs_files) - set(paths))
    if missing:
        errors.append(f"missing files from index: {missing[:5]} (total {len(missing)})")
    if extra:
        errors.append(f"extra mirror files not in index: {extra[:5]} (total {len(extra)})")
    if bad_bytes:
        errors.append(f"index byte mismatches: {bad_bytes[:5]} (total {len(bad_bytes)})")
    if bad_headers:
        errors.append(f"mirror files missing provenance header: {bad_headers[:5]} (total {len(bad_headers)})")
    if trailing_ws:
        errors.append(f"mirror files with trailing whitespace: {trailing_ws[:5]} (total {len(trailing_ws)})")

    discovered = index.get("discovered_pages")
    mirrored = index.get("mirrored_pages")
    failed = len(index.get("failed_pages") or [])
    if mirrored != len(pages):
        errors.append(f"mirrored_pages={mirrored} but index pages={len(pages)}")
    if mirrored != len(fs_files):
        errors.append(f"mirrored_pages={mirrored} but filesystem markdown files={len(fs_files)}")
    if isinstance(discovered, int) and discovered != mirrored + failed:
        errors.append(f"discovered_pages={discovered} but mirrored+failed={mirrored + failed}")
    return errors


def normalize_existing_mirror(references: Path) -> None:
    mirror_root = references / MIRROR_DIR_NAME
    for path in mirror_root.rglob("*.md"):
        original = path.read_text(encoding="utf-8", errors="replace")
        normalized = normalize_markdown(original)
        if normalized != original:
            path.write_text(normalized, encoding="utf-8")

    index_path = references / "client-docs-mirror-index.json"
    if index_path.is_file():
        index = json.loads(index_path.read_text(encoding="utf-8"))
        for item in index.get("pages") or []:
            rel = item.get("path")
            if rel and (references / rel).is_file():
                item["bytes"] = (references / rel).stat().st_size
        index["last_normalized_at"] = utc_now()
        index_path.write_text(json.dumps(index, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def refresh_mirror(skill_root: Path, allow_failures: bool) -> int:
    references = skill_root / "references"
    references.mkdir(parents=True, exist_ok=True)

    payload = fetch_json(DOC_DIRECTORY_API)
    docs: list[dict] = []
    for item in payload.get("data", {}).get("items", []):
        if item.get("name") in ROOT_NAMES:
            walk(item, [], docs)

    mirror_root = references / MIRROR_DIR_NAME
    staging_root = references / f".{MIRROR_DIR_NAME}.tmp"
    if staging_root.exists():
        shutil.rmtree(staging_root)
    staging_root.mkdir(parents=True)

    print(f"mirroring {len(docs)} markdown pages into {staging_root} ...", file=sys.stderr)
    mirror_results: list[dict] = []
    failures: list[str] = []
    try:
        with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
            futures = [executor.submit(mirror_one_doc, (doc, staging_root)) for doc in docs]
            for i, future in enumerate(concurrent.futures.as_completed(futures), start=1):
                try:
                    mirror_results.append(future.result())
                except Exception as exc:  # pragma: no cover - network dependent
                    failures.append(str(exc))
                if i % 100 == 0:
                    print(f"mirrored/fetched {i}/{len(futures)} pages", file=sys.stderr)

        failure_rate = (len(failures) / len(docs)) if docs else 0
        if failures and not allow_failures and failure_rate > FAILURE_RATE_LIMIT:
            raise SystemExit(
                f"mirror failure rate {failure_rate:.1%} exceeds {FAILURE_RATE_LIMIT:.1%}; rerun with --allow-failures to keep partial failures"
            )

        if mirror_root.exists():
            shutil.rmtree(mirror_root)
        staging_root.rename(mirror_root)

        mirror_index = references / "client-docs-mirror-index.json"
        mirror_index.write_text(
            json.dumps(
                {
                    "generated_at": utc_now(),
                    "crawler": "scripts/crawl_client_docs.py",
                    "directory_source": DOC_DIRECTORY_API,
                    "document_base": DOC_BASE,
                    "discovered_pages": len(docs),
                    "mirrored_pages": len(mirror_results),
                    "failed_pages": failures,
                    "pages": sorted(mirror_results, key=lambda item: item["source"]),
                },
                ensure_ascii=False,
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )

        catalog = references / "client-docs-source-catalog.md"
        catalog.write_text(build_catalog(docs, mirror_results, failures), encoding="utf-8")

        validation_errors = validate_mirror(references)
        if validation_errors:
            for error in validation_errors:
                print(f"validation error: {error}", file=sys.stderr)
            return 2

        if failures:
            print("mirror failures:", file=sys.stderr)
            for failure in failures[:20]:
                print(f"- {failure}", file=sys.stderr)
            if len(failures) > 20:
                print(f"- ... {len(failures) - 20} more", file=sys.stderr)
        print(f"wrote {catalog} with {len(docs)} document pages and mirrored {len(mirror_results)} pages")
        return 0
    finally:
        if staging_root.exists():
            shutil.rmtree(staging_root)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--validate", action="store_true", help="validate the existing local mirror without network access")
    parser.add_argument("--normalize", action="store_true", help="normalize existing mirror markdown whitespace and index byte counts")
    parser.add_argument("--allow-failures", action="store_true", help="accept partial fetch failures when refreshing the mirror")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    skill_root = Path(__file__).resolve().parents[1]
    references = skill_root / "references"

    if args.normalize:
        normalize_existing_mirror(references)

    if args.validate:
        errors = validate_mirror(references)
        if errors:
            for error in errors:
                print(f"validation error: {error}", file=sys.stderr)
            return 2
        print("client docs mirror validation passed")
        return 0

    return refresh_mirror(skill_root, allow_failures=args.allow_failures)


if __name__ == "__main__":
    raise SystemExit(main())
