#!/usr/bin/env python3
"""Refresh the Feishu/Lark client documentation mirror for this skill.

The Feishu/Lark documentation site can be hard for coding agents to browse
reliably during implementation. This script crawls the official Open Platform
documentation directory endpoint, indexes the Developer Guides and Client API
roots, and mirrors the official markdown page content under
``references/client-docs-mirror/`` so OpenCode, Codex, and other generic agents
can query the documentation from the installed skill files.
"""

from __future__ import annotations

import concurrent.futures
import hashlib
import json
import re
import shutil
import sys
import time
import urllib.parse
import urllib.request
from collections import defaultdict
from pathlib import Path

DOC_DIRECTORY_API = "https://open.feishu.cn/api/tools/docment/directory_list"
DOC_BASE = "https://open.feishu.cn/document"
ROOT_NAMES = {"\u5f00\u53d1\u6307\u5357": "Developer Guides", "\u5ba2\u6237\u7aef API": "Client API"}
USER_AGENT = "Hermes Feishu skill documentation crawler"
MIRROR_DIR_NAME = "client-docs-mirror"
MAX_WORKERS = 8


def fetch_json(url: str) -> dict:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode("utf-8"))



def fetch_text(url: str, attempts: int = 3) -> str:
    last_error: Exception | None = None
    for attempt in range(attempts):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
            with urllib.request.urlopen(req, timeout=45) as resp:
                return resp.read().decode("utf-8", "replace")
        except Exception as exc:  # pragma: no cover - network dependent
            last_error = exc
            time.sleep(0.5 * (attempt + 1))
    raise RuntimeError(f"failed to fetch {url}: {last_error}")


def safe_slug(text: str, fallback: str = "doc") -> str:
    text = urllib.parse.unquote(text)
    text = text.lower()
    text = re.sub(r"[^a-z0-9._-]+", "-", text)
    text = re.sub(r"-+", "-", text).strip("-._")
    return (text or fallback)[:80]


def mirror_path_for_doc(doc: dict) -> Path:
    encoded = percent_encode_path(doc["fullPath"])
    section = safe_slug(section_key(doc["fullPath"]), "section")
    digest = hashlib.sha1(encoded.encode("utf-8")).hexdigest()[:12]
    leaf = safe_slug(Path(doc["fullPath"]).name, "page")
    root = ROOT_NAMES.get(doc["trail"][0], "Other") if doc.get("trail") else "Other"
    root_slug = safe_slug(root, "root")
    return Path(MIRROR_DIR_NAME) / root_slug / section / f"{digest}-{leaf}.md"


def mirror_one_doc(args: tuple[dict, Path]) -> dict:
    doc, references = args
    encoded = percent_encode_path(doc["fullPath"])
    page_url = f"{DOC_BASE}{encoded}"
    markdown_url = f"{page_url}.md"
    rel_path = mirror_path_for_doc(doc)
    out_path = references / rel_path
    text = fetch_text(markdown_url)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    header = "\n".join([
        "<!--",
        "Mirrored official Feishu/Lark documentation page.",
        f"Source: {page_url}",
        f"Markdown source: {markdown_url}",
        "Generated by scripts/crawl_client_docs.py.",
        "-->",
        "",
    ])
    out_path.write_text(header + text.rstrip() + "\n", encoding="utf-8")
    return {
        "source": page_url,
        "markdown_source": markdown_url,
        "path": str(rel_path),
        "bytes": out_path.stat().st_size,
    }

def section_key(full_path: str) -> str:
    parts = [p for p in full_path.split("/") if p]
    known = [
        "platform-overveiw",
        "develop-robots",
        "uMTMuMTMuMTM",
        "docs-add-on",
        "base-extensions",
        "block",
        "development-link-preview",
        "feishu-cards",
        "native-integration",
        "web-app-open-ability",
        "mcp_open_tools",
    ]
    for key in known:
        if key in parts:
            return key
    return parts[-2] if len(parts) > 1 else (parts[0] if parts else "root")


def walk(node: dict, trail: list[str], docs: list[dict]) -> None:
    name = node.get("name", "")
    full_path = node.get("fullPath", "")
    new_trail = trail + [name]
    if node.get("type") == "DocumentType":
        docs.append({"name": name, "fullPath": full_path, "trail": new_trail})
    for child in node.get("items") or []:
        walk(child, new_trail, docs)


def percent_encode_path(path: str) -> str:
    return urllib.parse.quote(path, safe="/-._~ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789")


def main() -> int:
    skill_root = Path(__file__).resolve().parents[1]
    references = skill_root / "references"
    references.mkdir(parents=True, exist_ok=True)

    payload = fetch_json(DOC_DIRECTORY_API)
    docs: list[dict] = []
    for item in payload.get("data", {}).get("items", []):
        if item.get("name") in ROOT_NAMES:
            walk(item, [], docs)

    mirror_root = references / MIRROR_DIR_NAME
    if mirror_root.exists():
        shutil.rmtree(mirror_root)

    print(f"mirroring {len(docs)} markdown pages into {mirror_root} ...", file=sys.stderr)
    mirror_results: list[dict] = []
    failures: list[str] = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = [executor.submit(mirror_one_doc, (doc, references)) for doc in docs]
        for i, future in enumerate(concurrent.futures.as_completed(futures), start=1):
            try:
                mirror_results.append(future.result())
            except Exception as exc:  # pragma: no cover - network dependent
                failures.append(str(exc))
            if i % 100 == 0:
                print(f"mirrored/fetched {i}/{len(futures)} pages", file=sys.stderr)

    mirror_index = references / "client-docs-mirror-index.json"
    mirror_index.write_text(
        json.dumps(
            {
                "directory_source": DOC_DIRECTORY_API,
                "document_base": DOC_BASE,
                "discovered_pages": len(docs),
                "mirrored_pages": len(mirror_results),
                "failed_pages": failures,
                "pages": sorted(mirror_results, key=lambda item: item["source"]),
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    lines = [
        "# Feishu/Lark Client Documentation Source Catalog",
        "",
        "Generated from the official Open Platform directory endpoint and markdown page URLs. This file maps official pages to mirrored markdown files stored inside this skill for coding-agent search and offline access.",
        "",
        f"- Directory source: `{DOC_DIRECTORY_API}`",
        "- Starting page checked: `https://open.feishu.cn/document/client-docs/intro`",
        f"- Document pages discovered: {len(docs)}",
        f"- Document pages mirrored: {len(mirror_results)}",
        f"- Failed pages: {len(failures)}",
        "- Roots indexed: Developer Guides and Client API",
        "- Mirror index: `references/client-docs-mirror-index.json`",
        "- Mirror root: `references/client-docs-mirror/`",
        "",
    ]

    for root_cn, root_en in ROOT_NAMES.items():
        root_docs = [d for d in docs if d["trail"] and d["trail"][0] == root_cn]
        groups: dict[str, list[dict]] = defaultdict(list)
        for doc in root_docs:
            groups[section_key(doc["fullPath"])].append(doc)
        lines.extend([f"## {root_en}", ""])
        for section in sorted(groups):
            lines.extend([f"### `{section}`", ""])
            for doc in sorted(groups[section], key=lambda item: item["fullPath"]):
                encoded = percent_encode_path(doc["fullPath"])
                rel = mirror_path_for_doc(doc)
                lines.append(f"- `{encoded}` -> `{rel}` -> {DOC_BASE}{encoded}")
            lines.append("")

    catalog = references / "client-docs-source-catalog.md"
    catalog.write_text("\n".join(lines) + "\n", encoding="utf-8")

    text = catalog.read_text(encoding="utf-8")
    if re.search(r"[\u4e00-\u9fff]", text):
        raise SystemExit("generated catalog contains CJK characters; keep catalog headings English-only")
    if failures:
        print("mirror failures:", file=sys.stderr)
        for failure in failures[:20]:
            print(f"- {failure}", file=sys.stderr)
        if len(failures) > 20:
            print(f"- ... {len(failures) - 20} more", file=sys.stderr)
    print(f"wrote {catalog} with {len(docs)} document pages and mirrored {len(mirror_results)} pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
